### ISSUE TITLE
Unexpected token u

### ISSUE THREAD

**Issue by helske** [r-hub/rhub-frontend#13]
I just tried to use the R-hub builder website for the first time, and after uploading the package (`KFAS_1.0.4.tar.gz`), I tried to verify my e-mail via Github authorization, but after accepting, I get this:

![rhub](https://cloud.githubusercontent.com/assets/1560448/19110691/4faac96c-8af3-11e6-9c8b-678bc8a573a2.png)

And now this is all I see when I re-enter the site or try to click the links etc.

This happened both on Firefox and on Chrome (Windows 10). The email address in package description matches the one I use in Github.

**Comment by gaborcsardi** [comment]
Yes, the error message could be better. 

The problem is that GH validation only works if your primary GH email address is the same as the maintainer address.

**Comment by helske** [comment]
Thanks, I actually had the same email address, but apparently I had hidden my email address in Github, when I made that visible everything started working fine.

**Comment by gaborcsardi** [comment]
@helske Oh, OK, I did not know that, thanks for the info!
